### ISSUE TITLE
공항 정보

### ISSUE THREAD

**Issue by lalaalal** [lalaalal/AirportInfo#22]
![image](https://user-images.githubusercontent.com/39375299/204785641-e16aa4fe-634f-475c-b011-b4aed895c032.png)

1. 공항 설명은 자리만 만들어 두기
2. Info 에는 AirportDetailView 사용
3. Map 에는 GoogleMapAPI 사용
4. 이미지는 자리만 만들어 두기

```
AirportDetailContentView extends ContentView {
// 생성자에서 AirportController 받아와 멤버변수로 두기
// load메소드에서 AirportController.getSelectedAirport를 통해 공항 정보 보여주기
}
```

**Comment by ShinHeeYoun** [comment]
제가 해보겠습니다
